### ISSUE TITLE
win-update-tools.cmd not working on windows 10

### ISSUE THREAD

**Issue by dblhlx** [DrDonk/unlocker#3]
Platform: Windows 10 education, Python 3 not installed

VMWare workstation player 16 was successfully unlocked using unlocker 3.03. Thanks!
I encountered a problem when trying to fetch darwin.iso using win-update-tools.cmd. Here is the error message:

C:\Apps\unlocker>win-update-tools.cmd
Get macOS VMware Tools 3.0.3
===============================
(c) Dave Parsons 2011-21
VMware is installed at: C:\Program Files (x86)\VMware\VMware Workstation\
Getting VMware Tools...
Traceback (most recent call last):
  File "C:\Apps\unlocker\gettools.py", line 30, in <module>
    from urllib.request import urlopen
  File "<frozen zipimport>", line 259, in load_module
  File "urllib\request.py", line 88, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "http\client.py", line 71, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "email\parser.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "email\feedparser.py", line 27, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "email\_policybase.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "email\utils.py", line 29, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "socket.py", line 51, in <module>
ModuleNotFoundError: No module named '_socket'
Finished!

**Comment by DrDonk** [comment]
Thanks for the details. I'll take a look in a couple of days as I'm currently not in a position to test.

**Comment by WillPresley** [comment]
I was able to solve this issue by updating the python-win-embed-amd64 folder with the latest embeddable package version for Win-64 from here: https://www.python.org/downloads/windows/

**Comment by DrDonk** [comment]
Thanks for the info I will update my version.

**Comment by dblhlx** [comment]
Thanks, WillPresley!  I downloaded the Windows embeddable package (64-bit) version 3.95. It worked!

I test unlocker 3.03 on Deepin 20 using miniconda3 (Python 3.8.8). It worked perfectly. Thank you so much, DrDonk!

**Comment by DrDonk** [comment]
I just realised that I messed up GitHub checkin and it's missing a bunch of Python files including the socket DLL. I will fix and re-release as soon as I sort it out.

**Comment by DrDonk** [comment]
Version 3.0.4 now available
