### ISSUE TITLE
error in urllib2 & gettools

### ISSUE THREAD

**Issue by DarkC343** [DrDonk/unlocker#39]
Hi. I have just installed python 2.7 in windows 10 and I got this error while executing with administration privileges
............................
Getting VMware Tools...
Traceback (most recent call last):
  File "gettools.py", line 159, in <module>
    main()
  File "gettools.py", line 91, in main
    response = urlopen(url)
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 467, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 654, in http_error_302
  File "urllib2.py", line 435, in open
  File "urllib2.py", line 548, in http_response
  File "urllib2.py", line 473, in error
  File "urllib2.py", line 407, in _call_chain
  File "urllib2.py", line 556, in http_error_default
urllib2.HTTPError: HTTP Error 403: Forbidden
[10932] Failed to execute script gettools
............................
I also changed `chcp 850` to `chcp 936` but error occurred again.

**Comment by DarkC343** [comment]
Unfortunately, the problem was with the VMware website and it's access limitation for for Iranian people. Hopefully, running a proxy helped me to executing the script and all required packages were installed.
