### ISSUE TITLE
File Not Found on ESXi 6.7u3

### ISSUE THREAD

**Issue by rickdgray** [DrDonk/unlocker#8]
```
[root@ESXi:/golocker] ./unlocker install
Unlocker 4.1.0 for VMware Workstation/Player
============================================
© 2014-2021 David Parsons

VMware is installed at:  /usr/lib/vmware
VMware version:  .

Installing unlocker
Patching...
File: /usr/lib/vmware/lib/libvmwarebase.so/libvmwarebase.so Mode: 2
panic: Cannot find file

goroutine 18 [running]:
golocker/vmwpatch.mapFile({0xc000148040, 0x35}, 0xc00008c0a0)
        /Users/dave/Projects/lang-go/golocker/vmwpatch/utils.go:35 +0x14a
golocker/vmwpatch.IsGOSPatched({0xc000148040, 0xc00004868c})
        /Users/dave/Projects/lang-go/golocker/vmwpatch/gostable.go:100 +0x38
main.main.func1()
        /Users/dave/Projects/lang-go/golocker/command/unlocker.go:100 +0x305
created by main.main
        /Users/dave/Projects/lang-go/golocker/command/unlocker.go:82 +0x3dd
[root@ESXi:/vmfs/volumes/61e5ac7c-c1db28bc-f741-90b11c20baf0/golocker410/linux]
```

**Comment by rickdgray** [comment]
I see in the commits that MMap was replaced to fix some issues so I compiled latest locally and now have this issue:

```
[root@ESXi:/golocker] ./unlocker install
Unlocker 4.1.1 for VMware Workstation/Player
============================================
© 2014-2022 David Parsons

VMware is installed at:  /usr/lib/vmware
VMware version:  .

Installing unlocker.py
Patching...
File: /usr/lib/vmware/lib/libvmwarebase.so/libvmwarebase.so
panic: open /usr/lib/vmware/lib/libvmwarebase.so/libvmwarebase.so: no such file or directory

goroutine 18 [running]:
github.com/drdonk/golocker/vmwpatch.loadFile({0xc0000ce040, 0x35})
        /home/rdgray/golocker/vmwpatch/utils.go:21 +0x9a
github.com/drdonk/golocker/vmwpatch.IsGOSPatched({0xc0000ce040, 0x35})
        /home/rdgray/golocker/vmwpatch/gostable.go:97 +0x3b
main.main.func1()
        /home/rdgray/golocker/command/unlocker.go:100 +0x305
created by main.main
        /home/rdgray/golocker/command/unlocker.go:82 +0x3dd
[root@ESXi:/golocker]
```

Seems like the same result: libvmwarebase.so must be located elsewhere.

**Comment by DrDonk** [comment]
ESXi is not supported. Also Go executables do not run on ESXi VMkernel due to a difference in syscalls. VMware did some work on modifying Go compiler but not released. I am investigating this but for now the code will not work on ESXi.

ESXi also needs different files patching and a specific way to package the files as the root FS is read only.

**Comment by rickdgray** [comment]
Ok thanks for the update. I will stick to the python version.
